import AppKit
import Foundation

struct ClipboardPasteboardSnapshot {
    private enum Value {
        case data(Data)
        case propertyList(Any)
    }

    private struct Item {
        let values: [(type: NSPasteboard.PasteboardType, value: Value)]
    }

    let changeCount: Int
    private let items: [Item]

    var itemCount: Int {
        items.count
    }

    init(from pasteboard: NSPasteboard) {
        changeCount = pasteboard.changeCount
        items = (pasteboard.pasteboardItems ?? []).map { item in
            let values = item.types.compactMap { type -> (type: NSPasteboard.PasteboardType, value: Value)? in
                if let data = item.data(forType: type) {
                    return (type, .data(data))
                }
                if let propertyList = item.propertyList(forType: type) {
                    return (type, .propertyList(propertyList))
                }
                return nil
            }
            return Item(values: values)
        }
    }

    @discardableResult
    func restore(to pasteboard: NSPasteboard) -> Bool {
        _ = pasteboard.clearContents()
        guard !items.isEmpty else { return true }

        let restoredItems = items.map { snapshotItem in
            let item = NSPasteboardItem()
            for value in snapshotItem.values {
                switch value.value {
                case .data(let data):
                    item.setData(data, forType: value.type)
                case .propertyList(let propertyList):
                    item.setPropertyList(propertyList, forType: value.type)
                }
            }
            return item
        }
        return pasteboard.writeObjects(restoredItems)
    }

    @discardableResult
    func restore(
        to pasteboard: NSPasteboard,
        ifChangeCountIs expectedChangeCount: Int,
        andStringIs expectedString: String?
    ) -> Bool {
        guard pasteboard.changeCount == expectedChangeCount,
              pasteboard.string(forType: .string) == expectedString else {
            return false
        }
        return restore(to: pasteboard)
    }
}

struct ClipboardTransaction {
    static let markerType = NSPasteboard.PasteboardType("local.douvo.clipboard-transaction")

    let id: UUID
    let insertedText: String
    let insertedChangeCount: Int
    private let original: ClipboardPasteboardSnapshot

    var originalChangeCount: Int {
        original.changeCount
    }

    static func begin(
        text: String,
        in pasteboard: NSPasteboard = .general,
        source: String = Bundle.main.bundleIdentifier ?? "local.douvo.voice"
    ) -> ClipboardTransaction? {
        let original = ClipboardPasteboardSnapshot(from: pasteboard)
        let id = UUID()

        _ = pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString(id.uuidString, forType: markerType)
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        item.setString(source, forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))

        guard pasteboard.writeObjects([item]) else {
            _ = original.restore(to: pasteboard)
            return nil
        }

        return ClipboardTransaction(
            id: id,
            insertedText: text,
            insertedChangeCount: pasteboard.changeCount,
            original: original
        )
    }

    @discardableResult
    func restoreIfUnchanged(in pasteboard: NSPasteboard = .general) -> Bool {
        guard pasteboard.changeCount == insertedChangeCount else { return false }
        guard pasteboard.string(forType: .string) == insertedText else { return false }
        guard pasteboard.pasteboardItems?.count == 1,
              pasteboard.pasteboardItems?.first?.string(forType: Self.markerType) == id.uuidString else {
            return false
        }
        return original.restore(to: pasteboard)
    }
}
