import AppKit
import Foundation

@MainActor
enum PasteHelper {
    private static var nextRestoreID: UInt64 = 1
    private static var pendingRestoreID: UInt64?
    private static let restoreDelay: TimeInterval = 0.75

    static func copyAndPaste(_ text: String) {
        guard !text.isEmpty else { return }
        AppLog.info("PasteHelper copyAndPaste chars=\(text.count)")
        let restorePlan = copyForPaste(text)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            postCommandV()
            scheduleRestore(restorePlan)
        }
    }

    static func copyOnly(_ text: String) {
        guard !text.isEmpty else { return }
        AppLog.info("PasteHelper copyOnly chars=\(text.count)")
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    private static func copyForPaste(_ text: String) -> ClipboardRestorePlan {
        let pasteboard = NSPasteboard.general
        let restoreID = nextRestoreID
        nextRestoreID += 1
        pendingRestoreID = restoreID

        let previousText = pasteboard.string(forType: .string)
        let previousChangeCount = pasteboard.changeCount

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        item.setString(Bundle.main.bundleIdentifier ?? "local.doubao.voice", forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))
        pasteboard.writeObjects([item])
        let insertedChangeCount = pasteboard.changeCount

        return ClipboardRestorePlan(
            id: restoreID,
            insertedText: text,
            previousText: previousText,
            previousChangeCount: previousChangeCount,
            insertedChangeCount: insertedChangeCount
        )
    }

    private static func scheduleRestore(_ plan: ClipboardRestorePlan) {
        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
            restoreClipboardIfUnchanged(plan)
        }
    }

    private static func restoreClipboardIfUnchanged(_ plan: ClipboardRestorePlan) {
        guard pendingRestoreID == plan.id else { return }

        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount == plan.insertedChangeCount,
              pasteboard.string(forType: .string) == plan.insertedText else {
            AppLog.info("PasteHelper skip clipboard restore: clipboard changed")
            pendingRestoreID = nil
            return
        }

        pasteboard.clearContents()
        if let previousText = plan.previousText {
            pasteboard.setString(previousText, forType: .string)
        }
        pendingRestoreID = nil
        AppLog.info("PasteHelper clipboard restored previousChangeCount=\(plan.previousChangeCount)")
    }

    private static func postCommandV() {
        AppLog.info("PasteHelper posting Command-V")
        let source = CGEventSource(stateID: .hidSystemState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true)
        keyDown?.flags = .maskCommand
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }
}

private struct ClipboardRestorePlan {
    let id: UInt64
    let insertedText: String
    let previousText: String?
    let previousChangeCount: Int
    let insertedChangeCount: Int
}
